#!/usr/bin/env ruby

require 'dotenv'
require 'json'
require 'net/http'

class ToBRL
  def init
    check_api
    check_value
    return if usage.nil?

    brl = build_uri
    convert(brl, value)
  end

  private

  def check_api
    api_key
  end

  def load_api_key
    Dotenv.load(File.join(__dir__, '.env'))['API_KEY']
  end

  def api_key
    @api_key = load_api_key
  end

  def check_value
    value
  end

  def value
    @value = load_value
  end

  def load_value
    ARGV[0].to_f
  end

  def usage
    return puts 'Crie sua API key em https://openexchangerates.org/' if @api_key.nil?
    return puts "Uso: Adicione um valor.\nExemplo: `tobrl 12` para converter R$12 para USD" if @value.zero?
  end

  def build_uri
    uri = URI("https://openexchangerates.org/api/latest.json?app_id=#{@api_key}")
    fetch_uri(uri)
  end

  def fetch_uri(uri)
    result = Net::HTTP.get(uri)
    parse_result(result)
  end

  def parse_result(result)
    JSON.parse(result)
  end

  def convert(json, value)
    rates = json
    brl = rates['rates']['BRL'].to_f * value
    print_value(brl)
  end

  def print_value(brl)
    puts brl.truncate(2)
  end
end

ToBRL.new.init
