#!/usr/bin/env ruby

require 'dotenv'
require 'json'
require 'net/http'

api_key = Dotenv.load(File.join(__dir__, ".env"))['API_KEY']

if api_key.nil? || api_key.empty?
  puts "Crie sua API key em https://openexchangerates.org/"
  return
end

if ARGV.empty? || ARGV[0].to_f == 0.0
  puts "Uso: Adicione um valor."
  puts "Exemplo: `tobrl 12` para converter R$12 para USD"
else
  uri = URI("https://openexchangerates.org/api/latest.json?app_id=#{api_key}")
  rates = JSON.parse(Net::HTTP.get(uri))
  brl = rates["rates"]["BRL"].to_f * ARGV[0].to_f

  puts brl.truncate(2)

end
